version: '3.3'
services:
  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'dev-test'
      MYSQL_PASSWORD: 'rXHsG&4Nx954'
      MYSQL_ROOT_PASSWORD: '6MvWEgT6^91&'
    ports:
      - '3310:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: